### ISSUE TITLE
AttributeError: module 'imgaug.augmenters' has no attribute 'BlendAlphaSimplexNoise'

### ISSUE THREAD

**Issue by molo32** [shrubb/latent-pose-reenactment#18]
run.sh
```
# in this example, your images should be "$DATASET_ROOT/images-cropped/$IDENTITY_NAME/*.jpg"
DATASET_ROOT="/content/dataset"
IDENTITY_NAME="id00017"
MAX_BATCH_SIZE=8             # pick the largest possible, start with 8 and decrease until it fits in VRAM
CHECKPOINT_PATH="/content/latent-pose-reenactment/utils/latent-pose-release.pth"
OUTPUT_PATH="outputs/"       # a directory for outputs, will be created
RUN_NAME="tony_hawk_take_1"  # give your run a name if you want

# Important. See the note below
TARGET_NUM_ITERATIONS=230

# Don't change these
NUM_IMAGES=`ls -1 "$DATASET_ROOT/images-cropped/$IDENTITY_NAME" | wc -l`
BATCH_SIZE=$((NUM_IMAGES<MAX_BATCH_SIZE ? NUM_IMAGES : MAX_BATCH_SIZE))
ITERATIONS_IN_EPOCH=$(( NUM_IMAGES / BATCH_SIZE ))

mkdir -p $OUTPUT_PATH

python3 train.py \
    --config finetuning-base                 \
    --checkpoint_path "$CHECKPOINT_PATH"     \
    --data_root "$DATASET_ROOT"              \
    --train_split_path "$IDENTITY_NAME"      \
    --batch_size $BATCH_SIZE                 \
    --num_epochs $(( (TARGET_NUM_ITERATIONS + ITERATIONS_IN_EPOCH - 1) / ITERATIONS_IN_EPOCH )) \
    --experiments_dir "$OUTPUT_PATH"         \
```

```


!sudo bash /content/dataset/run.sh


PID 763 - 2021-03-26 01:46:58,894 - INFO - utils.load_config_file - Using config configs/finetuning-base.yaml
PID 763 - 2021-03-26 01:46:58,901 - INFO - utils.get_args_and_modules - Loading checkpoint file /content/latent-pose-reenactment/utils/latent-pose-release.pth
PID 763 - 2021-03-26 01:47:00,262 - INFO - utils.setup - Random Seed: 123
PID 763 - 2021-03-26 01:47:00,262 - INFO - train.py - Initialized the process group, my rank is 0
PID 763 - 2021-03-26 01:47:00,262 - INFO - train.py - Loading dataloader 'voxceleb2_segmentation_nolandmarks'
PID 763 - 2021-03-26 01:47:00,470 - INFO - dataloaders.common.voxceleb.get_part_data (train) - Determining the 'train' data source
PID 763 - 2021-03-26 01:47:00,470 - INFO - dataloaders.common.voxceleb.get_part_data (train) - Checking if '/content/dataset/images-cropped/id00017' is a directory...
PID 763 - 2021-03-26 01:47:00,471 - INFO - dataloaders.common.voxceleb.get_part_data (train) - Yes, it is; the only train identity will be 'id00017'
PID 763 - 2021-03-26 01:47:00,472 - INFO - dataloaders.common.voxceleb.get_part_data (train) - This dataset has 3 images
PID 763 - 2021-03-26 01:47:00,472 - INFO - dataloaders.common.voxceleb.get_part_data (train) - Setting `args.num_labels` to 1 because we are fine-tuning or the model has been fine-tuned
PID 763 - 2021-03-26 01:47:00,472 - WARNING - dataloader - Could not find the '.npy' file with bboxes, will assume the images are already cropped
PID 763 - 2021-03-26 01:47:00,473 - INFO - dataloaders.augmentation - Pixelwise augmentation: True
PID 763 - 2021-03-26 01:47:00,473 - INFO - dataloaders.augmentation - Affine scale augmentation: True
PID 763 - 2021-03-26 01:47:00,473 - INFO - dataloaders.augmentation - Affine shift augmentation: True
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    dataloader_train = m['dataloader'].get_dataloader(args, part='train', phase='train')
  File "/content/latent-pose-reenactment/dataloaders/dataloader.py", line 28, in get_dataloader
    dataset = self.dataset.get_dataset(args, part)
  File "/content/latent-pose-reenactment/dataloaders/voxceleb2_segmentation_nolandmarks.py", line 40, in get_dataset
    augmenter = augmentation.get_augmentation_seq(args)
  File "/content/latent-pose-reenactment/dataloaders/common/augmentation.py", line 24, in get_augmentation_seq
    return ParametricAugmenter(args)
  File "/content/latent-pose-reenactment/dataloaders/common/augmentation.py", line 60, in __init__
    iaa.BlendAlphaSimplexNoise(
AttributeError: module 'imgaug.augmenters' has no attribute 'BlendAlphaSimplexNoise'
```

**Comment by shrubb** [comment]
You must have not followed the [setup instructions](https://github.com/shrubb/latent-pose-reenactment#prerequisites) and so are running in an incompatible [environment](https://github.com/shrubb/latent-pose-reenactment/blob/master/INSTALL.md).
