### ISSUE TITLE
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by loboere** [shrubb/latent-pose-reenactment#36]
```
Wed Nov 17 06:44:26 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   31C    P8    28W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

%cd /content/latent-pose-reenactment/utils
!sudo bash /content/latent-pose-reenactment/utils/preprocess_dataset.sh

```
/content/latent-pose-reenactment/utils
/content/latent-pose-reenactment/utils
Got 1 folders, will process from 0-th to 999999999-th
0 images /content/dataset_ana2/images/ana ana
WARNING: /content/dataset_ana2/images-cropped/ana/ already exists, contains 0 files
Traceback (most recent call last):
  File "crop_as_in_dataset.py", line 680, in <module>
    cropper = ChosenFaceCropper((args.image_size, args.image_size))
  File "crop_as_in_dataset.py", line 211, in __init__
    self.face_detector = load_face_detector()
  File "crop_as_in_dataset.py", line 22, in load_face_detector
    return FaceDetector(device='cuda')
  File "/usr/local/lib/python3.7/dist-packages/face_alignment/detection/sfd/sfd_detector.py", line 31, in __init__
    self.face_detector.to(device)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by shrubb** [comment]
I suppose it's because of `sudo`, why are you using it?
