### ISSUE TITLE
Can we use the pretrained model to drive any arbitrary video?

### ISSUE THREAD

**Issue by ovshake** [shrubb/latent-pose-reenactment#37]
Hi, 
Thank you for your wonderful work! I was wondering, can we use the pre-trained model to drive a particular image? In the paper, it has been mentioned that the resulting images will have a lot of identity gaps. For the time being, I am not too worried about the identity gap, but would like to see the results. Currently, when I run, I am getting the error of `identity_embedding` missing in the pre-trained model. What `identity_embedding` was used to get results out of the pre-trained checkpoint? 
Thank you

**Comment by shrubb** [comment]
Hi, have you tried following the [manual](https://github.com/shrubb/latent-pose-reenactment/)? It has all steps that should work.

**Comment by ovshake** [comment]
Yes, I am following the manual. This is the code and the output. This command is working fine when I am using a fine-tuned checkpoint, but when I use the pretrained checkpoint, it is showing me the following error. I want to understand `identity_embedding` should I use to run on the pretrained checkpoint. 
```
> python drive.py checkpoints/latent-pose-release.pth  /home/users/abhishekm/temp/data_latent_pose --images_paths vc_t1/vc_t1 --destination outputs/vct1_meta
2022-02-25 21:54:06,047 - INFO - Will run on device 'cuda:0'
2022-02-25 21:54:06,047 - INFO - Loading checkpoint from 'checkpoints/latent-pose-release.pth'
2022-02-25 21:54:07,125 - INFO - Loading embedder 'unsupervised_pose_separate_embResNeXt_segmentation'
2022-02-25 21:54:11,237 - INFO - Loading generator 'vector_pose_unsupervised_segmentation_noBottleneck'
2022-02-25 21:54:11,852 - INFO - Loading discriminator 'no_landmarks'
Traceback (most recent call last):
  File "drive.py", line 68, in <module>
    generator.load_state_dict(running_averages['generator'])
  File "/home/users/abhishekm/anaconda3/envs/art-flow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 846, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Generator:
        Missing key(s) in state_dict: "identity_embedding".
```

**Comment by shrubb** [comment]
See #8 then

**Comment by ovshake** [comment]
Thank you, this solves my query. Wondering why this issue didn't come when I searched.
