### ISSUE TITLE
I got a TypeError when running 'drive.py',  can you help me see what's wrong. The opencv version is the same as yours (4.3.0.36).

### ISSUE THREAD

**Issue by supermusan** [shrubb/latent-pose-reenactment#4]
2020-11-18 15:02:37,009 - INFO - Will run on device 'cuda:0'
2020-11-18 15:02:37,009 - INFO - Loading checkpoint from '/data/home/wws/reenactment/latent-pose-reenactment/outputs/trump_cropface_1/checkpoints/model_02714323.pth'
2020-11-18 15:02:37,579 - INFO - Loading embedder 'unsupervised_pose_separate_embResNeXt_segmentation'
2020-11-18 15:02:41,966 - INFO - Loading generator 'vector_pose_unsupervised_segmentation_noBottleneck'
2020-11-18 15:02:42,804 - INFO - Loading discriminator 'no_landmarks'
2020-11-18 15:02:43,519 - INFO - Loading dataloader 'voxceleb2_segmentation_nolandmarks'
2020-11-18 15:02:43,942 - INFO - Determining the 'val' data source
2020-11-18 15:02:43,943 - INFO - Checking if '/data/home/wws/reenactment/latent-pose-reenactment/dataset/biden_videos/images-cropped/crop.mp4' is a directory...
2020-11-18 15:02:43,943 - INFO - Yes, it is; the only val identity will be 'crop.mp4'
2020-11-18 15:02:43,946 - INFO - This dataset has 326 images
2020-11-18 15:02:43,946 - INFO - Setting `args.num_labels` to 1 because we are fine-tuning or the model has been fine-tuned
2020-11-18 15:02:43,952 - WARNING - Could not find the '.npy' file with bboxes, will assume the images are already cropped
2020-11-18 15:02:43,952 - INFO - `args.inference` is set, so switching off all augmentations
2020-11-18 15:02:43,953 - INFO - This process will receive a dataset with 326 samples
  0%|                                                                                                                                              | 0/326 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "drive.py", line 94, in <module>
    result = torch_to_opencv(data_dict['fake_rgbs'][0])
  File "drive.py", line 92, in torch_to_opencv
    return cv2.cvtColor(image, cv2.COLOR_RGB2BGR, dst=image)
TypeError: Expected Ptr<cv::UMat> for argument 'dst'

**Comment by shrubb** [comment]
Hm. Hard to say why this happens. As a workaround, can you try removing `, dst=image` from line 92 and let me know if that worked?

If anyone has the same issue, please post here, I'll then try to look into this.

**Comment by supermusan** [comment]
It works, but a new problem has arisen.

2020-11-18 15:25:03,553 - INFO - Will run on device 'cuda:0'
2020-11-18 15:25:03,554 - INFO - Loading checkpoint from '/data/home/wws/reenactment/latent-pose-
reenactment/outputs/trump_cropface_1/checkpoints/model_02714323.pth'
2020-11-18 15:25:04,191 - INFO - Loading embedder 'unsupervised_pose_separate_embResNeXt_segmentation'
2020-11-18 15:25:43,455 - INFO - Loading generator 'vector_pose_unsupervised_segmentation_noBottleneck'
2020-11-18 15:25:44,554 - INFO - Loading discriminator 'no_landmarks'
2020-11-18 15:25:45,265 - INFO - Loading dataloader 'voxceleb2_segmentation_nolandmarks'
2020-11-18 15:25:52,995 - INFO - Determining the 'val' data source
2020-11-18 15:25:52,996 - INFO - Checking if '/data/home/wws/reenactment/latent-pose-reenactment/dataset/biden_videos/images-cropped/crop.mp4' is a directory...
2020-11-18 15:25:52,996 - INFO - Yes, it is; the only val identity will be 'crop.mp4'
2020-11-18 15:25:53,069 - INFO - This dataset has 326 images
2020-11-18 15:25:53,069 - INFO - Setting `args.num_labels` to 1 because we are fine-tuning or the model has been fine-tuned
2020-11-18 15:25:53,089 - WARNING - Could not find the '.npy' file with bboxes, will assume the images are already cropped
2020-11-18 15:25:53,089 - INFO - `args.inference` is set, so switching off all augmentations
2020-11-18 15:25:53,091 - INFO - This process will receive a dataset with 326 samples
  0%|                                                                                                                                              | 0/326 [00:00<?, ?it/s]Could not find encoder for codec id 27: Encoder not found
  0%|                                                                                                                                              | 0/326 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "drive.py", line 98, in <module>
    image_writer.add(frame_grid)
  File "/data/home/wws/reenactment/latent-pose-reenactment/utils/crop_as_in_dataset.py", line 616, in add
    assert self.video_writer.isOpened(), "Couldn't initialize video writer"
AssertionError: Couldn't initialize video writer

**Comment by shrubb** [comment]
What you see is skvark/opencv-python#207 (your OpenCV was built without ffmpeg support).

You may either fix that, or modify this:

https://github.com/shrubb/latent-pose-reenactment/blob/59629a64105c7c33fa01c461a3c65d3690f8533c/drive.py#L80-L82

according to this:

https://github.com/shrubb/latent-pose-reenactment/blob/59629a64105c7c33fa01c461a3c65d3690f8533c/utils/crop_as_in_dataset.py#L585-L595

**Comment by supermusan** [comment]
Thanks!

> What you see is [skvark/opencv-python#207](https://github.com/skvark/opencv-python/issues/207) (your OpenCV was built without ffmpeg support).
> 
> You may either fix that, or modify this:
> 
> https://github.com/shrubb/latent-pose-reenactment/blob/59629a64105c7c33fa01c461a3c65d3690f8533c/drive.py#L80-L82
> 
> according to this:
> 
> https://github.com/shrubb/latent-pose-reenactment/blob/59629a64105c7c33fa01c461a3c65d3690f8533c/utils/crop_as_in_dataset.py#L585-L595

**Comment by pfeducode** [comment]
How did you solve your problem? I don't understand. Where did you modify it.

**Comment by pfeducode** [comment]
> 

I remove the dst=image,  and it work well.  I don't know why.

**Comment by joytsay** [comment]
for anyone who want to know how to fix the:
```
assert self.video_writer.isOpened(), "Couldn't initialize video writer"
AssertionError: Couldn't initialize video writer
```

you can replace line:
https://github.com/shrubb/latent-pose-reenactment/blob/59629a64105c7c33fa01c461a3c65d3690f8533c/utils/crop_as_in_dataset.py#L607

with:
`self.fourcc = cv2.VideoWriter_fourcc(*'mp4v')`

and it will be good to go!



> It works, but a new problem has arisen.
> 
> 2020-11-18 15:25:03,553 - INFO - Will run on device 'cuda:0' 2020-11-18 15:25:03,554 - INFO - Loading checkpoint from '/data/home/wws/reenactment/latent-pose- reenactment/outputs/trump_cropface_1/checkpoints/model_02714323.pth' 2020-11-18 15:25:04,191 - INFO - Loading embedder 'unsupervised_pose_separate_embResNeXt_segmentation' 2020-11-18 15:25:43,455 - INFO - Loading generator 'vector_pose_unsupervised_segmentation_noBottleneck' 2020-11-18 15:25:44,554 - INFO - Loading discriminator 'no_landmarks' 2020-11-18 15:25:45,265 - INFO - Loading dataloader 'voxceleb2_segmentation_nolandmarks' 2020-11-18 15:25:52,995 - INFO - Determining the 'val' data source 2020-11-18 15:25:52,996 - INFO - Checking if '/data/home/wws/reenactment/latent-pose-reenactment/dataset/biden_videos/images-cropped/crop.mp4' is a directory... 2020-11-18 15:25:52,996 - INFO - Yes, it is; the only val identity will be 'crop.mp4' 2020-11-18 15:25:53,069 - INFO - This dataset has 326 images 2020-11-18 15:25:53,069 - INFO - Setting `args.num_labels` to 1 because we are fine-tuning or the model has been fine-tuned 2020-11-18 15:25:53,089 - WARNING - Could not find the '.npy' file with bboxes, will assume the images are already cropped 2020-11-18 15:25:53,089 - INFO - `args.inference` is set, so switching off all augmentations 2020-11-18 15:25:53,091 - INFO - This process will receive a dataset with 326 samples 0%| | 0/326 [00:00<?, ?it/s]Could not find encoder for codec id 27: Encoder not found 0%| | 0/326 [00:01<?, ?it/s] Traceback (most recent call last): File "drive.py", line 98, in image_writer.add(frame_grid) File "/data/home/wws/reenactment/latent-pose-reenactment/utils/crop_as_in_dataset.py", line 616, in add assert self.video_writer.isOpened(), "Couldn't initialize video writer" AssertionError: Couldn't initialize video writer
